In [13]:
#2D array
import numpy as np
m1=np.array([[5,10],[11,6]])
m2=np.array([[1,7],[6,5]])
m3=m1+m2
print(m3)

[[ 6 17]
 [17 11]]


In [14]:
print(m1)
print(np.transpose(m1))

[[ 5 10]
 [11  6]]
[[ 5 11]
 [10  6]]


In [15]:
print(m2)
print(np.transpose(m2))

[[1 7]
 [6 5]]
[[1 6]
 [7 5]]


In [78]:
#KNN
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

col=['sepal_length','sepal_width','petal_length','petal_width','class']
dataset=pd.read_csv('iris.csv',names=col)
dataset.head()

sepal_length  sepal_width  petal_length  petal_width   class
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [79]:
#"sepal.length","sepal.width","petal.length","petal.width","variety"
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [81]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [82]:
from sklearn.metrics import accuracy_score
print("Accuracy : ")
print(accuracy_score(y_test,y_pred))

Accuracy : 
0.9666666666666667


In [83]:
from sklearn.metrics import confusion_matrix
print("confusion matrix : ")
print(confusion_matrix(y_test,y_pred))

confusion matrix : 
[[ 9  0  0]
 [ 0 13  1]
 [ 0  0  7]]


In [84]:
from sklearn.metrics import classification_report
print("classification report: ")
print(classification_report(y_test, y_pred))

classification report: 
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         9
  Versicolor       1.00      0.93      0.96        14
   Virginica       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.98      0.97        30
weighted avg       0.97      0.97      0.97        30

